services:
  redis:
    image: redis:latest

  publisher:
    build: .
    command: uvicorn publisher:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  subscriber:
    build: .
    command: python -u subscriber.py
    depends_on:
      - redis